### ISSUE TITLE
How do i download?

### ISSUE THREAD

**Issue by Elisjeeh** [TheBusyBiscuit/ExtraGear#10]
How would i add this plugin to my server?

**Comment by Elisjeeh** [comment]
(I mean this as in what do i need to download?)

**Comment by TheBusyBiscuit** [comment]
You can find a download link here:
https://github.com/TheBusyBiscuit/Slimefun4/wiki/Addons
Just drag and drop the jar into your plugins folder.

(Assuming you already installed CS-CoreLib and Slimefun, otherwise go here: https://github.com/TheBusyBiscuit/Slimefun4/wiki/Installing-Slimefun )

And please DO NOT abuse the bug tracker for questions. This is only for bug reports.

**Comment by Elisjeeh** [comment]
> You can find a download link here:
> https://github.com/TheBusyBiscuit/Slimefun4/wiki/Addons
> Just drag and drop the jar into your plugins folder.
> 
> (Assuming you already installed CS-CoreLib and Slimefun, otherwise go here: https://github.com/TheBusyBiscuit/Slimefun4/wiki/Installing-Slimefun )
> 
> And please DO NOT abuse the bug tracker for questions. This is only for bug reports.

Im sorry but i cant find any .jar files.
